part of 'models.dart';

enum SubscriptionRenewalStatus {
  @JsonValue('auto-renew')
  autoRenew,
  canceled,
}

enum SubscriptionStatus { active, expired, pending }

@freezed
class StorableSubscription with _$StorableSubscription {
  factory StorableSubscription({
    /// This is the ID of the subscription. It should generated by your database.
    /// And should be unique (Primary Key).
    required String id,

    /// It's the unique transaction id.
    required String transactionId,

    /// The product that the user purchased. This is used to grant user access levels.
    required String productId,

    /// The store that the user purchased the subscription from.
    required SubscriptionStore source,

    /// The unique user id provided in the app to identify the user. This should be
    /// linked to the user table in your database.
    required String customerEmail,

    /// The time the subscription will expire.
    required DateTime expiresAt,

    /// The time the subscription was purchased.
    /// This will get updated when subscription is renewed.
    required DateTime purchaseDate,

    /// Subscriptions's renewal status
    required SubscriptionRenewalStatus renewalStatus,

    /// The status of the subscription
    required SubscriptionStatus status,
  }) = _StorableSubscription;

  factory StorableSubscription.fromJson(Map<String, dynamic> json) =>
      _$StorableSubscriptionFromJson(json);
}
