part of 'models.dart';

enum SubscriptionRenewalStatus {
  @JsonValue('auto_renew')
  autoRenew,
  canceled,
}

enum SubscriptionStatus {
  active,
  @JsonValue('on_hold')
  onHold,
  @JsonValue('grace_period')
  gracePeriod,
  trialing,
  expired
}

int _dateToEpochMilliseconds(DateTime date) => date.millisecondsSinceEpoch;

@freezed
class StorableSubscription with _$StorableSubscription {
  factory StorableSubscription({
    /// This is the ID of the subscription. It should generated by your database.
    /// And should be unique (Primary Key).
    required String id,
    @JsonKey(name: 'product_id')

    /// The product that the user purchased. This is used to grant user access levels.
    required String productId,
    @JsonKey(
      name: 'expires_at',
      fromJson: DateTime.fromMillisecondsSinceEpoch,
      toJson: _dateToEpochMilliseconds,
    )

    /// The time the subscription will expire.
    required DateTime expiresAt,

    /// The store that the user purchased the subscription from.
    required SubscriptionStore store,

    /// The status of the subscription
    required SubscriptionStatus status,
    @JsonKey(name: 'renewal_status')

    /// Subscriptions's renewal status
    required SubscriptionRenewalStatus renewalStatus,
  }) = _StorableSubscription;

  factory StorableSubscription.fromJson(Map<String, dynamic> json) =>
      _$StorableSubscriptionFromJson(json);
}
